# Generated by Django 5.2.5 on 2025-09-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_books', models.BooleanField(default=False)),
                ('can_delete_books', models.BooleanField(default=False)),
                ('can_view_books', models.BooleanField(default=False)),
                ('can_edit_books', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_view_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Custom Permission',
                'verbose_name_plural': 'Custom Permissions',
            },
        ),
    ]
